lane_detector:
  ros__parameters:
    debug: False
    image_topic: "/zed/zed_node/rgb/image_rect_color"
    # image_topic: "/zed/zed_node/right/image_rect_color"
    disable_topic: "/temp_disable"

# All tests on lane 4
pure_pursuit:
  ros__parameters:
    debug: True
    drive_topic: "/vesc/high_level/input/nav_0"
    # max_speed: 4.0
    # low_pass_cutoff_freq: 15.0
    # # base_lookahead: 3.9
    # base_lookahead: 4.5
    # lookahead_speed_ratio: 0.0
    # # base_lookahead: 5.0
    # # eta_multiplier: 1.5
    # eta_multiplier: 1.15
    # # eta_multiplier: 1.25
    # # eta_multiplier: 1.4
    # Kp: 0.0
    # # Kd: 0.125  # Oscillates more
    # Kd: 0.1
    # Kd: 0.08  # Oscillates a bit more

    # Follows and is slightly damping in straights, works at 4 m/s on lane 4
    max_speed: 4.0
    low_pass_cutoff_freq: 15.0
    base_lookahead: 4.5
    lookahead_speed_ratio: 0.0
    eta_multiplier: 1.15
    Kp: 0.0
    Kd: 0.1

    # Works at 3 m/s on lane 2
    # max_speed: 3.0
    # low_pass_cutoff_freq: 15.0
    # base_lookahead: 3.3
    # lookahead_speed_ratio: 0.0
    # eta_multiplier: 1.0
    # Kp: 0.0
    # Kd: 0.1

    # Works at 4 m/s with some oscillating on lanes probably 2, tested on 4, probably 6 (but rollback code!)
    # max_speed: 4.0
    # low_pass_cutoff_freq: 15.0
    # base_lookahead: 3.9
    # lookahead_speed_ratio: 0.0
    # eta_multiplier: 1.0
    # Kp: 0.0
    # Kd: 0.1
    disable_topic: "/temp_disable"

visualizer_node:
  ros__parameters:
    debug: False
    fast_mode: True
    image_topic: "/zed/zed_node/rgb/image_rect_color"
    # image_topic: "/zed/zed_node/right/image_rect_color"

safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    ackermann_cmd_topic: "/vesc/low_level/ackermann_cmd"
    safety_topic: "/vesc/low_level/input/safety"
    disable_topic: "/temp_disable"
    temp_disable_timeout: 0.1
    stopping_time: 0.7
