lane_detector:
  ros__parameters:
    debug: False
    image_topic: "/zed/zed_node/rgb/image_rect_color"
    disable_topic: "/temp_disable"

# All tests on lane 4
pure_pursuit:
  ros__parameters:
    debug: True
    drive_topic: "/vesc/high_level/input/nav_0"
    max_speed: 4.0
    # max_speed: 2.5
    # max_speed: 1.0
    low_pass_cutoff_freq: 40.0  # workd
    # low_pass_cutoff_freq: 4.0
    # base_lookahead: 1.5
    # lookahead_speed_ratio: 0.75
    base_lookahead: 1.5  # worked
    lookahead_speed_ratio: 0.6  # worked
    # base_lookahead: 1.5
    # lookahead_speed_ratio: 0.5
    disable_topic: "/temp_disable"

visualizer_node:
  ros__parameters:
    debug: False
    fast_mode: True
    image_topic: "/zed/zed_node/rgb/image_rect_color"

safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    ackermann_cmd_topic: "/vesc/low_level/ackermann_cmd"
    safety_topic: "/vesc/low_level/input/safety"
    disable_topic: "/temp_disable"
    temp_disable_timeout: 0.1
    stopping_time: 0.7
