ros__parameters:
  scan_topic: "/scan"
  wall_follower_topic: "/vesc/high_level/input/nav_0"
  safety_controller_topic: "/vesc/input/safety"
  drive_topic: "drive"
  side: -1
  velocity: 1.0
  desired_distance: 1.
  
