safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    ackermann_cmd_topic: "vesc/low_level/ackermann_cmd"
    safety_topic: "vesc/low_level/input/safety"
    stopping_time: 0.7
    watchdog_period: 0.1

wall_follower:
  ros__parameters:
    scan_topic: "/scan"
    wall_follower_topic: "/vesc/high_level/input/nav_0"
    debug: 1
    side: -1
    velocity: 1.0
    desired_distance: 1.0
    Kp: 0.75
    Kd: 0.1
    Ap: 0.2
