safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    ackermann_cmd_topic: "/wall_follower_topic"
    safety_topic: "/safety_topic"
    stopping_time: 0.7
    watchdog_period: 0.1

wall_follower:
  ros__parameters:
    scan_topic: "/scan"
    wall_follower_topic: "/wall_follower_topic"
    debug: 1
    side: -1
    velocity: 1.0
    desired_distance: 1.0
    Kp: 5.7
    Ap: 4.0

sim_drive_mux:
  ros__parameters:
    safety_controller_topic: "/safety_topic"
    wall_follower_topic: "/wall_follower_topic"
    drive_topic: "/drive"
