trajectory_planner:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"
    debug: true

trajectory_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/high_level/input/nav_0"
    debug: true

safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    ackermann_cmd_topic: "/vesc/low_level/ackermann_cmd"
    safety_topic: "/vesc/low_level/input/safety"
    watchdog_localize_topic: "/pf/pose/odom"
