trajectory_planner:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"

trajectory_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/high_level/input/nav_0"

safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    ackermann_cmd_topic: "/vesc/low_level/ackermann_cmd"
    safety_topic: "/vesc/low_level/input/safety"
    stopping_time: 0.7
    watchdog_period: 0.1
